<blockquote>
<br>
<h2 class="head">News</h2>


<table cellpadding="3" cellspacing="0" align="center" width="100%" summary="" class="container">
<tr class="newsheader">
<td width="150">2009-11-08 21:45</td>
<td>GGC Update 0.4.10.1</td>
</tr>
<tr>
<td colspan="2">
As one of users noticed, there was minor/major problem in configuration. There was problem with 
configuration of Unit for Blood Glucose. It wouldn't be a problem for old users, but it is/was for 
for new users. This is now fixed. If you are old user (and don't plan to change BG unit) you don't 
need to apply it. 
</td>
</tr>
</table> 

<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" summary="" class="container">
<tr class="newsheader">
<td width="150">2009-10-31 22:45</td>
<td>GGC Update 0.4.10</td>
</tr>
<tr>
<td colspan="2">
I am again only one developing so this update is little late. We plan to have another release by end 
of year, but since I am only developer at this time (we need more people, so if you know java or have
ideas, please contact us), development is just slowly progressing...<br>
We fixed some bugs in this update, and implemented application mode (either pump or pen/injection), 
which changes toolbar and display different statistics (not working yet for pump mode). A lot of work 
was done on Pump Tool, we have added some devices (Dana fully, Roche partitialy) and also changed 
some stuff on manual entry (TBRs, Food entries, fixed Bolus Helper). 
</td>
</tr>
</table> 

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" summary="" class="container">
<tr class="newsheader">
<td width="150">2009-10-31 22:45</td>
<td>Translation Tool update</td>
</tr>
<tr>
<td colspan="2">
Translation Tool is in works, we are currently working on next "internal" version. It should be finished
and ready for all end-users who wish to translate our software in their own language soon. Plan is to 
release it sometime in November or in start of December.
</td>
</tr>
</table> 

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" summary="" class="container">
<tr class="newsheader">
<td width="150">2009-06-18 14:00</td>
<td>Next release update</td>
</tr>
<tr>
<td colspan="2">
Since we didn't reach any of "special" goals we decided to postpone 0.5 release till end of year 
(probably till December). This doesn't mean that you won't get any updates, but there will be just
minor updates (0.4.x), which don't require database changes.<br>
Next minor update is planned for start of July and it will contain much revised Pump Tool with possible
support for reading data from some devices.<br>
We are most actively working now on Pump Tool and we also started Translation Tool subproject which 
is intended for people willing to translate this software. So far translation is messy and not 
really intended for non-developers, but this will change with this new tool, which will come out
arround September 2009 and will simplify translation.
</td>
</tr>
</table> 


<br><br>



<table cellpadding="3" cellspacing="0" align="center" width="100%" summary="" class="container">
<tr class="newsheader">
<td width="150">2009-05-10 14:00</td>
<td>Translations update</td>
</tr>
<tr>
<td colspan="2">
We created special document for "How To Translate GGC". See Documentation.
</td>
</tr>
</table> 


<br><br>



<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2009-04-02 21:00</td>
<td>GGC 0.4.3 Update</td>
</tr>
<tr>
<td colspan="2">
Update makes changes to HbA1c Dialog, Printing system and Startup system, also there has been change to 
Nutrition part (we now have dynamic loading of data, so startup is faster).
</td>
</tr>
</table> 


<br><br>




<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2009-02-14 11:00</td>
<td>About versioning of GGC</td>
</tr>
<tr>
<td colspan="2">
As you can see, we are still in 0.x versions. We now had two releases, which both work, but yet we are still in 
so called pre-versions (bellow 1.0). <br>
Problem is that we "tagged" several features, we need/want to have implemented before we put out "real" 1.0 
release. If everything goes alright this will happen with next release (0.5)...
</td>
</tr>
</table> 


<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2009-02-14 10:00</td>
<td>Release 0.4 OUT</td>
</tr>
<tr>
<td colspan="2">
We have finally brought you next GGC release (this time we are just over a month late...). New version features
changes in main gui, additional food support (we support free-text food entries), Bolus Helper (and Simple Ratios
for that), new graph framework, Meter Tool finsihed (and new devices added), development of Pump Tool started 
(Manual adding of data only, so far). <br>
There were also several changes to this web page, added files to Documentation, changed Screenshots, Downloads, 
Features. 
</td></tr>
</table> 



<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-12-24 22:44</td>
<td>Release 0.4 comming out soon</td>
</tr>
<tr>
<td colspan="2">
After first public release it was decided, that there will be one major release every six months, 
at least until we finish all main functionalities. Next release will come out in January 2009,
with some major changes and lots of minor ones.<br>
As you can see, we are still in 0.x versions. When all tagged (required) functionalities are finished, 
we will go to version 1.0 (this might happen with release 0.5 or maybe 0.6).  
</td></tr>
</table> 

<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-12-24 18:00</td>
<td>Best wishes for next year</td>
</tr>
<tr>
<td colspan="2">
Merry Christmas (Happy Hanukkah) and Happy New Year 2009 for all Diabetics, their loved ones and all other people.<br>
GGC Development Team
</td></tr>
</table> 

<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-12-01 4:44</td>
<td>New developers</td>
</tr>
<tr>
<td colspan="2">
In last few months, we gathered several new developers, which will help us with development
of several parts of GGC, so please welcome them.<br>
So welcome Aleksander Balaban (support for Meter OT UltraSmart and other stuff), Magnus Odell (Support for
Animas pump and other stuff) and Tom S. (translation to French and some other stuff).
</td></tr>
</table> 

<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-08-04 22:44</td>
<td>Release 0.3 out</td>
</tr>
<tr>
<td colspan="2">
And its finally here... Our first public release. As promissed, we added two more features to all previously planned ones. 
Meter Tool is now released (supported are currently just Ascensia/Bayer) and full Backup and Restore is possible. More about
all current and planned features on page 'Features'.
</td></tr>
</table> 

<br><br>



<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-07-06 18:44</td>
<td>Release by end of month July 2008</td>
</tr>
<tr>
<td colspan="2">
We planned to have application ready by 4th of July, but we are still behind our release plan. This, vacations, RL (Real life)
keep interfering with our release. We have just minimal stuff to do, so release WILL BE out by end of month. We wanted to 
implement Restore Db function, so that updates will be possible in the future. We intend to implement special update service,
but this might be months away. 
</td></tr>
</table> 

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-05-30 10:44</td>
<td>Release postponed (for one month)</td>
</tr>
<tr>
<td colspan="2">
Release was planned for 4th of June 2008, but due to some problems we are forced to postpone it for a month. To repay you 
for waiting another month, we decided to add two features, which were planned for next release (which ones is surprise). 
</td></tr>
</table>

<br><br>



<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-04-20 16:44</td>
<td>Update to web page</td>
</tr>
<tr>
<td colspan="2">
Major update of this web page. All pages were changed, and added were 'Sub-Projects' and 'Help Us' pages.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-02-10 19:50</td>
<td>New Preview release</td>
</tr>
<tr>
<td colspan="2">
First public release (0.2.9.6). This is just preview (Alpha) version for first major release, planned in near 
future. (4th April 2008)
</td></tr>
</table>

<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2006-03-01 09:22</td>
<td>New developer</td>
</tr>
<tr>
<td colspan="2">
New developer rumbi joined the team and is taking testing and linux specific development.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2005-04-04 10:44</td>
<td>New developer</td>
</tr>
<tr>
<td colspan="2">
New developer andyrozman joined the team and is taking over main development of project.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 19:51</td>
<td>New project homepage</td>
</tr>
<tr>
<td colspan="2">
We have a brand new homepage. Check it out.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 19:50</td>
<td>First alpha released</td>
</tr>
<tr>
<td colspan="2">
Today, we released a first public alpha version.<br><br>
It is a developer release but you are welcome to test it.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 15:17</td>
<td>Homepage is on its way</td>
</tr>
<tr>
<td colspan="2">
A brand new homepage with screenshots, information ans stuff like that, is on its way.<br><br>
Check back to see it.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-07-16 16:07</td>
<td>sources now in cvs</td>
</tr>
<tr>
<td colspan="2">
Today I put the current development sources into cvs. Check them out if you want, but don't expect too much for now. It's still a very early alpha.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-03-25 23:06</td>
<td>Project started</td>
</tr>
<tr>
<td colspan="2">
Today we opened the project.
</td></tr>
</table>

<br><br>

<blockquote>
