<h2 class="header">Screenshots</h2>

Shots from Version "0.0.1alpha":

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/main.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Main Window</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/dailystats.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Day Window</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/dailygraph.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Day Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/course.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Course Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/spread.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Spread Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/frequency.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Frequency Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/hba1c.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>HbA1c</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./shots/prefs.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Preferences</td></tr>
</table>