<blockquote>
<br>
<h2 class="header">Support</h2>
If you need help or you want to contact us, there are different ways. They are in the order you should use (best first).<br><br>

<ol>
	<li><b>Mailing lists:</li></b><br>
	At the moment we have 3 different lists:<br><br>
	<ul>
		<li>ggc-user:</li><br>
		This is the first place to ask your general questions.<br><br>
		<li>ggc-developer:</li><br>
		This list is mainly for the developers of the project. Use this if you have a technical 
                question, or want to participate in development.<br><br>
		<li>ggc-cvs:</li><br>
		This is no "real" list. Every CVS/SVN activity generates mail in this list. Subscribe to it only
                if you wish to get messages, whenever files are changed or added.</ul>
                <br><br>
	Here is the link to the mailing list site:<br>
	<a href="http://sourceforge.net/mail/?group_id=49749">http://sourceforge.net/mail/?group_id=49749</a><br><br><br>
	<li><b>Forums:</li></b><br>
	We have some forums set up at Sourceforge. Check them:<br>
	<a href="http://sourceforge.net/forum/?group_id=49749">http://sourceforge.net/forum/?group_id=49749</a><br><br><br>
	<li><b>Trackers:</b></li><br>
	We have a Bug-Tracker, Support-Tracker, Feature-Request-Tracker and a Patch-Tracker. Use the one that fits best:<br>
	<a href="http://sourceforge.net/tracker/?group_id=49749">http://sourceforge.net/tracker/?group_id=49749</a><br><br><br>
	<li><b>Send us a mail:</li></b><br>
	<ul>
		<li>Andy (Aleksander) Rožman <<a href="mailto:andyrozman@users.sourceforge.net">andyrozman at users.sourceforge.net</a>></li>
		<li>Reinhold Rumberger <<a href="mailto:rumbi@users.sourceforge.net">rumbi at users.sourceforge.net</a>></li>
		<li>Dieter Schultschik <<a href="mailto:schultd@users.sourceforge.net">schultd at users.sourceforge.net</a>></li>
	</ul>
</ol>
</blockquote>
