<blockquote>
<br>
<h2 class="head">News</h2>




<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-08-04 22:44</td>
<td>Release 0.3 out</td>
</tr>
<tr>
<td colspan="2">
And its finally here... Our first public release. As promissed, we added two more features to all previously planned ones. 
Meter Tool is now released (supported are currently just Ascensia/Bayer) and full Backup and Restore is possible. More about
all current and planned features on page 'Features'.
</td></tr>
</table> 

<br><br>



<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-07-06 18:44</td>
<td>Release by end of month July 2008</td>
</tr>
<tr>
<td colspan="2">
We planned to have application ready by 4th of July, but we are still behind our release plan. This, vacations, RL (Real life)
keep interfering with our release. We have just minimal stuff to do, so release WILL BE out by end of month. We wanted to 
implement Restore Db function, so that updates will be possible in the future. We intend to implement special update service,
but this might be months away. 
</td></tr>
</table> 

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-05-30 10:44</td>
<td>Release postponed (for one month)</td>
</tr>
<tr>
<td colspan="2">
Release was planned for 4th of June 2008, but due to some problems we are forced to postpone it for a month. To repay you 
for waiting another month, we decided to add two features, which were planned for next release (which ones is surprise). 
</td></tr>
</table>

<br><br>



<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-04-20 16:44</td>
<td>Update to web page</td>
</tr>
<tr>
<td colspan="2">
Major update of this web page. All pages were changed, and added were 'Sub-Projects' and 'Help Us' pages.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-02-10 19:50</td>
<td>New Preview release</td>
</tr>
<tr>
<td colspan="2">
First public release (0.2.9.6). This is just preview (Alpha) version for first major release, planned in near 
future. (4th April 2008)
</td></tr>
</table>

<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2006-03-01 09:22</td>
<td>New developer</td>
</tr>
<tr>
<td colspan="2">
New developer rumbi joined the team and is taking testing and linux specific development.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2005-04-04 10:44</td>
<td>New developer</td>
</tr>
<tr>
<td colspan="2">
New developer andyrozman joined the team and is taking over main development of project.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 19:51</td>
<td>New project homepage</td>
</tr>
<tr>
<td colspan="2">
We have a brand new homepage. Check it out.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 19:50</td>
<td>First alpha released</td>
</tr>
<tr>
<td colspan="2">
Today, we released a first public alpha version.<br><br>
It is a developer release but you are welcome to test it.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 15:17</td>
<td>Homepage is on its way</td>
</tr>
<tr>
<td colspan="2">
A brand new homepage with screenshots, information ans stuff like that, is on its way.<br><br>
Check back to see it.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-07-16 16:07</td>
<td>sources now in cvs</td>
</tr>
<tr>
<td colspan="2">
Today I put the current development sources into cvs. Check them out if you want, but don't expect too much for now. It's still a very early alpha.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-03-25 23:06</td>
<td>Project started</td>
</tr>
<tr>
<td colspan="2">
Today we opened the project.
</td></tr>
</table>

<br><br>

<blockquote>
