<blockquote>
<br>
<h1 class="header">Download</h1>

<br>
<h2>Packaged software</h2>

This is preffered way of getting software (intended for all end users). In short you need to download package and install it. 
This is easier done on Windows platform, since we have installer, and little harder for all other platforms. There are detailed 
instructions in instalation package (see \docs folder, files Readme_1st and Readme, this 2 files are translated into german and
slovene (as is application)).

<h3>GGC Releases</h3>

<h4>Version 0.3</h4>

<ul>
<li><a href="http://downloads.sourceforge.net/ggc/GGC_Setup_0.3_jre.exe?use_mirror=osdn">GGC 0.3 Windows Installer (with JRE)</a> - You should use this 
install file if you have no knowledge about Java. It contains JRE, so the file is much bigger, but you can just install it, out-of-the-box,
without any special intervention (advised for most end-users).</li>

<li><a href="http://downloads.sourceforge.net/ggc/GGC_Setup_0.3.exe?use_mirror=osdn">GGC 0.3 Windows Installer (without JRE)</a> - If you have Java 
already on your computer, and your knowledge of computer is above average you can decide to take this file and manually configure 
application to run with your installed Java.</li>

<li><a href="http://downloads.sourceforge.net/ggc/GGC_0.3.zip?use_mirror=osdn">GGC 0.3 Zip file</a>, with all files - For all other platforms you need
to use this file. You just extract it and then follow by reading Readme_1st to get it running.</li>


</ul>


<h3>USB Releases</h3>

<h4>GGC USB Version</h4>
<ul>
<li><!-- a href="http://downloads.sourceforge.net/ggc/GGC_0.2.9.7.zip">GGC 0.3</a> -->
USB Release is not available at this time, but it will be added by end of September
</li>
</ul>


<h4>USB VMs</h4>
<ul>
<li><a href="http://downloads.sourceforge.net/ggc/Windows_16.zip?use_mirror=osdn">Windows VM [Java 1.6]</a></li>
<li><a href="http://downloads.sourceforge.net/ggc/Linux_16.zip?use_mirror=osdn">Linux VM [Java 1.6]</a></li>
<li><a href="http://downloads.sourceforge.net/ggc/FreeBSD_v7_16.zip?use_mirror=osdn">FreeBSD VM (FreeBSD 7.0) [Java 1.6]</a></li>
</ul>



<h3>Other files</h3>


<h4>USDA Nutrition Database</h4>

<ul>
<li><a href="http://downloads.sourceforge.net/ggc/USDA_Nutrient_Db_for_Standard_Reference_r18.zip?use_mirror=kent">USDA Nutrition Database 18</a> - Our software supports any of USDA databases, but since we are using some of data here imported (Home Weights), we are still little bit dependant. If you will start with your own User database, you should install newer version, but for some of here supplied User Databases, you will need specific versions. We will remove this dependency in the future, but for now our "Supported" version is still 18.</li>
</ul>


<h4>Custom Nutrition Databases</h4>

<ul>
<li><a href="http://downloads.sourceforge.net/ggc/SLO_Db_1.zip?use_mirror=osdn">Slovenian Nutrition Database 1</a> - This is nutrition database for people living in Slovenia and speaking Slovenian. All instructions and notes are inside zip archive. Required USDA SR-18.</li>
</ul>



<br>
<h2>Build from source</h2>

If you are Java developer, you will probably try to build whole thing from source code. All our current code is in SVN (we 
used CVS few years back). If you are not ready for a challenge, then try to download packaged software release. There will 
be pause between releases (6 months or more for major releases, minor releases will be released, when needed changes are 
done).


<ul>

<li>SVN:</li><br>
        SVN system is current versioning system. You neeed to pull down whole tree. When builing with ANT,
        compiled files will be stored into ggc-support\bin folder from where you can directly run it.<br>

	Here is the link to the Sourceforge SVN Page:<br>
	<a href="http://sourceforge.net/svn/?group_id=49749">http://sourceforge.net/svn/?group_id=49749</a> <br><br>
	For details on how to check out sources see the Sourceforge SVN page.<br><br>

<li>CVS:</li><br>
        CVS system was deprecated (there are still old file there) when Sourceforge installed SVN, which is now the way to get sources.<br><br>
	<a href="http://sourceforge.net/cvs/?group_id=49749">http://sourceforge.net/cvs/?group_id=49749</a> <br><br>

</ul>

<br>
<h2>Link to sourceforge files download area</h2>
	
        <a href="http://sourceforge.net/project/showfiles.php?group_id=49749">http://sourceforge.net/project/showfiles.php?group_id=49749</a><br>


</ul>
</blockquote>
