<blockquote>

<h2 class="header">Documentation</h2>
<br>
We have already produced quite a few documents, which are all packaged in releases of GGC or 
in SVN, but now they will also be here. Some of them are translated, but not all of them.<br>
<br><br>

<h2>GGC Application</h2>

<a href="docs/README.en">README</a> - Main GGC documentation (<a href="docs/README.de">German</a>, <a href="docs/README.si">Slovene</a>)<br>
<a href="docs/How_Can_I_Help.txt">How Can I Help</a> - This are detailed instructions on how to create build environment, prepare computer for making translation,...<br>
<a href="docs/Changelog">Changelog</a> - Document of changes (detailed)<br> 
<a href="docs/IDEAS.txt">Ideas</a> - Misc ideas of developers<br>
<a href="docs/TO-DO.txt">To-Do</a> - Detailed To-do list<br>
<br>
<a href="docs/README_1st_v2">README 1st</a> - This are detailed instruction on how application startup functions work, and how Java works in itself and how it works with native libraries or hybrids (<!a href="docs/README_1st_v2.de">German<!/a>, <!a href="docs/README_1st_v2.si">Slovene<!/a>)<br>
<a href="docs/README_1st">README 1st (old one)</a> - This is first version of Readme 1st which can help you, but most stuff is better explained in new one (<a href="docs/README_1st.de">German</a>, <a href="docs/README_1st.si">Slovene</a>)<br>

<a href="docs/Diabetes_Hardware.txt">Supported Diabetes Hardware</a> - List of supported hardware.




<a href="docs/"></a>


<h3>Update</h3>
<a href="docs/database_info.txt">Database Info</a> - Information of Database versions across all versions of GGC.
<br>
<a href="docs/Update_0.3.1.txt">Information on Update 0.3.1</a> - Instructions on how to update from GGC 0.3 to 0.3.1 (this is required update before we update 0.3 to upper versions ( 
<a href="docs/Update_0.3.1_de.txt">German</a>, 
<a href="docs/Update_0.3.1_si.txt">Slovene</a>)<br>

<a href="docs/How_To_Upgrade.txt">How to Upgrade</a> - Instructions on how to upgrade. If you have GGC 0.3, you need to do upgrade to 0.3.1 first. (
<a href="docs/How_To_Upgrade_de.txt">German</a>, 
<a href="docs/How_To_Upgrade_si.txt">Slovene</a>)<br>



<h3>USB</h3>


<a href="docs/USB-How-To.txt">USB How To</a> - Instructions on how to use GGC on USB (
<a href="docs/USB-How-To_de.txt">German</a>, 
<a href="docs/USB-How-To_si.txt">Slovene</a>)

<h3>Translation</h3>
<a href="docs/How_To_Translate_GGC.txt">How to Translate</a>. Now that GGC updates are comming out regulary, we have to 
come back to one of most difficult parts - translation. There are no tools in java to help with translations, so we have 
to make our own. Currently there are two simple tools that can help with translation, but still most of stuff must be 
done "manually". For this purpose we have here detailed document on how to help with translations. We are trying to create
tool that will simplify this process, but this might take quite some time. So for now here are dfetailed, step by step 
instructions. [Added on 10th May 2009]<br>

<br><br><br>

<h2>GGC Meter Tool</h2>

No official documentation available at this point.
<br><br>


<h2>GGC Pump Tool</h2>

No official documentation available at this point.

<br><br>

</blockquote>