<h2 class="header">Support</h2>
If you need help or you want to contact us, there are different ways. They are in the order you should use (best first).<br>
<ol>
	<li>Check our mailing lists:</li><br>
	At the moment we feature 3 different lists:<br><br>
	<ul>
		<li>ggc-user:</li><br>
		This is the first place to ask your general questions.<br><br>
		<li>ggc-developer:</li><br>
		This list is mainly for the developers of the project. Use this if you have a technical question, or want to participate in development.<br><br>
		<li>ggc-cvs:</li><br>
		This is no "real" list. Every CVS activity generates mail in this list. Read it if you want to stay on the bleeding edge, or you are a developer.<	</ul><br><br>
	Here is the link to the mailing list site:<br>
	<a href="http://sourceforge.net/mail/?group_id=49749">http://sourceforge.net/mail/?group_id=49749</a><br><br>
	<li>Check our forums:</li><br>
	We have some forums set up at Sourceforge. Check them:<br>
	<a href="http://sourceforge.net/forum/?group_id=49749">http://sourceforge.net/forum/?group_id=49749</a><br><br>
	<li>Check our Trackers:</li><br>
	We have a Bug-Tracker, Support-Tracker, Feature-Request-Tracker and a Patch-Tracker. Use the one that fits best:<br>
	<a href="http://sourceforge.net/tracker/?group_id=49749">http://sourceforge.net/tracker/?group_id=49749</a><br><br>
	<li>Send us a mail:</li><br>
	<ul>
		<li>Dieter Schultschik <<a href="mailto:schultd@users.sourceforge.net">schultschik at users.sourceforge.net</a>></li>
		<li>M. Aaron Wadley <<a href="mailto:cyberlizard@users.sourceforge.net">cyberlizard at users.sourceforge.net</a>> (Not active developer anymore)</li>
		<li>Aleksander (Andy) Rozman <<a href="mailto:andyrozman@users.sourceforge.net">andyrozman at users.sourceforge.net</a>></li>
		<li>Reinhold Rumberger <<a href="mailto:rumbi@users.sourceforge.net">rumbi at users.sourceforge.net</a>></li>
	</ul>
</ol>
