<blockquote>


<center><h2 class="header">Screenshots [Graphs]</h2></center>


<h3>

<a href="index.php?show=screenshots" class="menu">Screenshots Main</a><br>

<a href="index.php?show=screenshots_daily" class="menu">Injection/Pen Theraphy</a><br>

Graphs<br>

<a href="index.php?show=screenshots_tools" class="menu">Tools (Settings, Db)</a><br>

<a href="index.php?show=screenshots_print" class="menu">Printing</a><br>

<a href="index.php?show=screenshots_meter_tool" class="menu">Meter Tool</a><br>

<a href="index.php?show=screenshots_pump_tool" class="menu">Pump Tool</a><br>

<a href="index.php?show=screenshots_old" class="menu">Old Screenshots</a><br>

</h3>


<br>
<hr>
<br>


<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/daily_graph.jpg" border="0" alt="Daily Graph"></td></tr>
<tr><td>Daily Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/course_graph.jpg" border="0" alt="Course Graph"></td></tr>
<tr><td>Course Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/spread_graph.jpg" border="0" alt="Spread Graph"></td></tr>
<tr><td>Spread Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/calculated_hba1c.jpg" border="0" alt="Calculated HbA1c"></td></tr>
<tr><td>Calculated HbA1c</td></tr>
</table>

<br>


</blockquote>