<blockquote>


<center><h2 class="header">Screenshots [Injection/Pen Theraphy]</h2></center>


<h3>

<a href="index.php?show=screenshots" class="menu">Screenshots Main</a><br>

Injection/Pen Theraphy<br>

<a href="index.php?show=screenshots_graph" class="menu">Graphs</a><br>

<a href="index.php?show=screenshots_tools" class="menu">Tools (Settings, Db)</a><br>

<a href="index.php?show=screenshots_print" class="menu">Printing</a><br>

<a href="index.php?show=screenshots_meter_tool" class="menu">Meter Tool</a><br>

<a href="index.php?show=screenshots_pump_tool" class="menu">Pump Tool</a><br>

<a href="index.php?show=screenshots_old" class="menu">Old Screenshots</a><br>

</h3>


<br>
<hr>
<br>



<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/daily_stats_pen.jpg" border="0" alt="Daily Stats for Injection/Pen Theraphy"></td></tr>
<tr><td>Daily Stats for Injection/Pen Theraphy</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/add_entry.jpg" border="0" alt="Adding Daily Entry"></td></tr>
<tr><td>Adding Daily Entry</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/daily_graph.jpg" border="0" alt="Daily Graph"></td></tr>
<tr><td>Daily Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/bolus_helper.jpg" border="0" alt="Bolus Helper"></td></tr>
<tr><td>Bolus Helper</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/meals_selector.jpg" border="0" alt="Adding Food from Database"></td></tr>
<tr><td>Adding Food from Database</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/food_by_desc.jpg" border="0" alt="Adding Food by Description"></td></tr>
<tr><td>Adding Food by Description</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/basic_ratio.jpg" border="0" alt="Basic Ratio"></td></tr>
<tr><td>Basic Ratio - for calculating Bolus [for Bolus Helper]</td></tr>
</table>

<br>
<br>


<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/usda_db.gif" border="0" alt="USDA Database"></td></tr>
<tr><td>USDA Database (one of food databases, meals one looks the same)</td></tr>
</table>


<br>
<br>


</blockquote>