<blockquote>

<h2 class="header">Screenshots</h2>

Shots from Version "0.2.9.9" (most of them):

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/main.gif" border="0" alt="Main Window"></td></tr>
<tr><td>Main Window</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/dailystats.gif" border="0" alt="Day Window"></td></tr>
<tr><td>Day Window</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/dailygraph.gif" border="0" alt="Day Graph"></td></tr>
<tr><td>Day Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/course.jpg" border="0" alt="Main Window"></td></tr>
<tr><td>Course Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/spread.jpg" border="0" alt="Spread Graph"></td></tr>
<tr><td>Spread Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/frequency.jpg" border="0" alt="Frequency Graph"></td></tr>
<tr><td>Frequency Graph</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/hba1c.jpg" border="0" alt="HbA1c"></td></tr>
<tr><td>HbA1c</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/prefs.gif" border="0" alt="Preferences"></td></tr>
<tr><td>Preferences</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/usda_db.gif" border="0" alt="USDA Database"></td></tr>
<tr><td>USDA Database</td></tr>
</table>


<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/print_prepare.gif" border="0" alt="Printing (prepare)"></td></tr>
<tr><td>Printing (prepare)</td></tr>
</table>


<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/print_simple.gif" border="0" alt="Printing - Simple report (in Acrobat Viewer)"></td></tr>
<tr><td>Printing - Simple report (in Acrobat Viewer)</td></tr>
</table>


<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/print_extended.gif" border="0" alt="Printing - Extended report (in Acrobat Viewer)"></td></tr>
<tr><td>Printing - Extended report (in Acrobat Viewer)</td></tr>
</table>

</blockquote>