<h2 class="head">News</h2>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2008-02-10 19:50</td>
<td>New Preview release</td>
</tr>
<tr>
<td colspan="2">
First public release (0.2.9.6). This is just preview (Alpha) version for first major release, planned in near 
future. (4th April 2008)
</td></tr>
</table>

<br><br>


<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2006-03-01 09:22</td>
<td>New developer</td>
</tr>
<tr>
<td colspan="2">
New developer rumbi joined the team and is taking testing and linux specific development.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2005-04-04 10:44</td>
<td>New developer</td>
</tr>
<tr>
<td colspan="2">
New developer andyrozman joined the team and is taking over main development of project.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 19:51</td>
<td>New project homepage</td>
</tr>
<tr>
<td colspan="2">
We have a brand new homepage. Check it out.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 19:50</td>
<td>First alpha released</td>
</tr>
<tr>
<td colspan="2">
Today, we released a first public alpha version.<br><br>
It is a developer release but you are welcome to test it.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-08-01 15:17</td>
<td>Homepage is on its way</td>
</tr>
<tr>
<td colspan="2">
A brand new homepage with screenshots, information ans stuff like that, is on its way.<br><br>
Check back to see it.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-07-16 16:07</td>
<td>sources now in cvs</td>
</tr>
<tr>
<td colspan="2">
Today I put the current development sources into cvs. Check them out if you want, but don't expect too much for now. It's still a very early alpha.
</td></tr>
</table>

<br><br>

<table cellpadding="3" cellspacing="0" align="center" width="100%" class="container">
<tr class="newsheader">
<td width="150">2002-03-25 23:06</td>
<td>Project started</td>
</tr>
<tr>
<td colspan="2">
Today we opened the project.
</td></tr>
</table>

<br><br>
