<blockquote>

<center><h2 class="header">Screenshots [Tools (Settings, Db)]</h2></center>


<h3>

<a href="index.php?show=screenshots" class="menu">Screenshots Main</a><br>

<a href="index.php?show=screenshots_daily" class="menu">Injection/Pen Theraphy</a><br>

<a href="index.php?show=screenshots_graph" class="menu">Graphs</a><br>

Tools (Settings, Db)<br>

<a href="index.php?show=screenshots_print" class="menu">Printing</a><br>

<a href="index.php?show=screenshots_meter_tool" class="menu">Meter Tool</a><br>

<a href="index.php?show=screenshots_pump_tool" class="menu">Pump Tool</a><br>

<a href="index.php?show=screenshots_old" class="menu">Old Screenshots</a><br>

</h3>


<br>
<hr>
<br>



<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/prefs.gif" border="0" alt="Preferences"></td></tr>
<tr><td>Preferences</td></tr>
</table>

<br>
<br>



<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/backup_db.jpg" border="0" alt="Backup Database"></td></tr>
<tr><td>Backup Database</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/restore_db_1.jpg" border="0" alt="Restore Database 1"></td></tr>
<tr><td>Restore Database 1</td></tr>
</table>

<br>
<br>


<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/restore_db_2.jpg" border="0" alt="Restore Database 2"></td></tr>
<tr><td>Restore Database 2</td></tr>
</table>

<br>
<br>



<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/update.jpg" border="0" alt="Update GGC"></td></tr>
<tr><td>Update GGC</td></tr>
</table>

<br>
<br>





</blockquote>