<blockquote>
    <br>

    <h1 class="header">Download</h1>

    <br>

    <h2>Packaged software</h2>

    This is preffered way of getting software (intended for all end users). In short you need to download package and
    install it. This is easier done on Windows platform, since we have installer, and little harder for all other
    platforms. There are detailed instructions in instalation package (see \docs folder, files Readme_1st and Readme,
    this 2 files are translated into german and slovene (as is application)).
    <br><br><br>
    In each release there are 4 files:
    <ul>
        <li><b>GGC_Setup_&lt;Version Number&gt;_jre.exe - This is Windows installer with Java.</b> You should use this
            install
            file if you have no knowledge about Java. It contains JRE, so the file is much bigger, but you can just
            install it, out-of-the-box, without any special intervention (advised for most end-users).. [This is
            recomended option for Windows Users]
        </li>

        <li><b>GGC_Setup_&lt;Version Number&gt;.exe - This is windows installer without Java.</b> Download this if you
            have
            Java already
            on computer and your knowledge of computers is above average (you might need to configure java to run with
            application).
        </li>

        <li><b>GGC_&lt;Version Number&gt;.zip - (Full) Zip file containing all the files.</b> This is for all other
            platforms.
            You just extract it and then follow by reading Readme_1st to get it running. (in short you need to enter bin
            folder and run "run_
            <platform>" file, platform is either win, linux, mac or freebsd).
        </li>

        <li><b>GGC_Upgrade_&lt;Version Number&gt;.zip - Upgrade Zip file.</b> If you have installed previous version of
            GGC
            (version 0.3.1
            and above) and already have data stored in it, this is the file you need to use. Read document
            'How_To_Upgrade.txt'
            in zip file. (This file should be used only by users who know basic of O.S. they are using. Please make
            backup
            first before you attempt any update. <br><b>NOTE:</b> If you are not sure if you can do upgrade, you can do
            following: backup all data (Tools -> Database maintenance -> Backup) from previous version, install new
            version
            and then do restore (Tools -> Database maintenance -> Restore) of data.
        </li>
    </ul>


    <h3>GGC Releases</h3>

    <h4>Version 0.7.0 [June 2016 (Windows inst. added on September 2016)]</h4>

    <b>Note: During creation of 0.7.0 release, installers created are not working correctly. If you encounter problem
        starting application, please do the following: <br>
        1. Download 0.7.0_Update package<br>
        2. Extract files into some temporary location<br>
        3. Copy content of folder lib/hibernate3 to same folder in your GGC installation (there are 3 files missing in 0.7 install)<br>
        4. On next start application should work correctly<br>
    </b>

    <ul>
        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.7.0/GGC_Setup_0.7.0_jre.exe/download">
                GGC 0.7.0 - Windows Installer with Java [Preferred for Windows users]</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.7.0/GGC_Setup_0.7.0.exe/download">
                GGC 0.7.0 - Windows Installer without Java</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.7.0/GGC_0.7.0.zip/download">GGC
                0.7.0 (Full) Zip file</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.7.0/GGC_Update_0.7.0.zip/download">GGC
                0.7.0 Update Zip file</a>
        </li>
    </ul>


    <h4>Version 0.6.1 [October 2015]</h4>

    <ul>
        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.6.1/GGC_Update_0.6.1.zip/download">GGC
                0.6.1 Update Zip file</a>
        </li>

    </ul>

    <h4>Version 0.6.0 [August 2015]</h4>

    <ul>
        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.6.0/GGC_Setup_0.6.0_jre.exe/download">
                GGC 0.6.0 - Windows Installer with Java [Preferred for Windows users]</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.6.0/GGC_Setup_0.6.0.exe/download">
                GGC 0.6.0 - Windows Installer without Java</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.6.0/GGC_0.6.0.zip/download">GGC
                0.6.0 (Full) Zip file</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.6.0/GGC_Update_0.6.0.zip/download">GGC
                0.6.0 Update Zip file</a>
        </li>

    </ul>


    <h4>Version 0.5.0.3 [May 2014] (fixed release September 2014) </h4>

    <ul>
        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.5.0.3-2/GGC_Setup_0.5.0.3-2_jre.exe/download">
                GGC 0.5.0.3 (release 2) Windows Installer with Java</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.5.0.3-2/GGC_Setup_0.5.0.3-2.exe/download">
                GGC 0.5.0.3 (release 2) Windows Installer without Java</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.5.0.3-2/GGC_0.5.0.3-2.zip/download">GGC
                0.5.0.3 (release 2) (Full) Zip file</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.5.0.3-2/GGC_Update_0.5.0.3-2.zip/download">GGC
                Update 0.5.0.3 (release 2) Zip file</a>
        </li>

    </ul>


    <h4>Version 0.4 Updates</h4>


    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/GGC_Update_0.4.10.1.zip?use_mirror=osdn">GGC 0.4.10.1
            Update</a> -
            This is minor fix, for configuration (there was problem with setting BG unit, which might be problematic for
            new
            users). Old users don't need to install this (unless they want to change BG Unit).
        </li>
    </ul>


    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/GGC_Update_0.4.10.zip?use_mirror=osdn">GGC 0.4.10 Update</a> -
            This update makes changes
            to main application (application mode), and some bug fixes on all parts. Most changes were done on Pump Tool
            (added devices,
            changes made to manual adding).
        </li>
    </ul>


    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/GGC_Update_0.4.3.zip?use_mirror=osdn">GGC 0.4.3 Update</a> -
            This update makes changes
            to HbA1c Dialog, Printing system and Startup system, also there has been change to Nutrition part (we now
            have dynamic loading of data,
            so startup is faster).
        </li>
    </ul>

    <h4>Version 0.4</h4>

    <ul>
        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.4/GGC_Setup_0.4_jre.exe/download">
                GGC 0.4 Windows Installer with Java</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.4/GGC_Setup_0.4.exe/download">
                GGC 0.4 Windows Installer without Java</a>
        </li>

        <li><a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.4/GGC_0.4.zip/download">
            GGC 0.4 (Full) Zip file</a>
        </li>

        <li>
            <a href="http://sourceforge.net/projects/ggc/files/GNU%20Gluco%20Control/GGC%200.4/GGC_Update_0.4.zip/download">
                GGC Update 0.4 Zip file</a>
        </li>

    </ul>


    <h4>Version 0.3.1</h4>

    <ul>

        <li><a href="http://downloads.sourceforge.net/ggc/GGC_Update_0.3.1.zip?use_mirror=osdn">Update 0.3.1</a> - This
            update is needed if you plan to update your GGC from version 0.3. If you don't have any data in 0.3, it
            would be wiser to uninstall 0.3 and install one of higher versions.
        </li>
    </ul>


    <h4>Version 0.3</h4>

    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/GGC_Setup_0.3_jre.exe?use_mirror=osdn">GGC 0.3 Windows
            Installer with Java [Preferred for Windows users]</a>
        </li>

        <li><a href="http://downloads.sourceforge.net/ggc/GGC_Setup_0.3.exe?use_mirror=osdn">GGC 0.3 Windows Installer
            without Java</a>
        </li>

        <li><a href="http://downloads.sourceforge.net/ggc/GGC_0.3.zip?use_mirror=osdn">GGC 0.3 (Full) Zip file</a>
        </li>


    </ul>


    <br>

    <h3>USB Releases</h3>

    <h4>GGC USB Version</h4>
    <ul>
        <li>USB Releases are the same as full releases. Download any of them, and extract them from zip file, then
            download one of GVM releases (for version 0.4 and higher) or VM releases (for version 0.3).
            /li>
    </ul>


    <h4>USB GVMs (from 0.4 up) - Full</h4>


    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/GVM_linux_x86_1.zip?use_mirror=osdn">Linux GVM [Java 1.6]</a>
        </li>
        <li><a href="http://downloads.sourceforge.net/ggc/GVM_win_1.zip?use_mirror=osdn">Windows GVM [Java 1.6]</a></li>
        <li><a href="http://downloads.sourceforge.net/ggc/GVM_freebsd_1.zip?use_mirror=osdn">FreeBSD GVM [Java 1.6]</a>
        </li>
    </ul>


    <h4>USB GVMs (from 0.4 up) - Lite</h4>

    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/GVM_freebsd_lite_1.zip?use_mirror=osdn">FreeBSD Lite GVM</a>
        </li>
        <li><a href="http://downloads.sourceforge.net/ggc/GVM_mac_lite_1.zip?use_mirror=osdn">Mac Lite GVM</a></li>
    </ul>


    <h4>USB VMs (this were used for 0.3 version only)</h4>
    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/Windows_16.zip?use_mirror=osdn">Windows VM [Java 1.6]</a></li>
        <li><a href="http://downloads.sourceforge.net/ggc/Linux_16.zip?use_mirror=osdn">Linux VM [Java 1.6]</a></li>
        <li><a href="http://downloads.sourceforge.net/ggc/FreeBSD_v7_16.zip?use_mirror=osdn">FreeBSD VM (FreeBSD 7.0)
            [Java 1.6]</a></li>
    </ul>


    <br>

    <h3>Other files</h3>


    <h4>USDA Nutrition Database</h4>

    <ul>
        <li>
            <a href="http://downloads.sourceforge.net/ggc/USDA_Nutrient_Db_for_Standard_Reference_r18.zip?use_mirror=kent">USDA
                Nutrition Database 18</a> - Our software supports any of USDA databases, but since we are using some of
            data here imported (Home Weights), we are still little bit dependant. If you will start with your own User
            database, you should install newer version, but for some of here supplied User Databases, you will need
            specific versions. We will remove this dependency in the future, but for now our "Supported" version is
            still 18.
        </li>
    </ul>


    <h4>Custom Nutrition Databases</h4>

    <ul>
        <li><a href="http://downloads.sourceforge.net/ggc/SLO_Db_1.zip?use_mirror=osdn">Slovenian Nutrition Database
            1</a> - This is nutrition database for people living in Slovenia and speaking Slovenian. All instructions
            and notes are inside zip archive. Required USDA SR-18. Contains database from diabetes software Kocka.
        </li>
        <li><a href="http://downloads.sourceforge.net/ggc/SLO_Db_2.zip?use_mirror=osdn">Slovenian Nutrition Database
            2</a> - This is nutrition database for people living in Slovenia and speaking Slovenian. All instructions
            and notes are inside zip archive. Required USDA SR-18. Contains databases from 2 different Slovenian
            programs: Kocka and Daciofit
        </li>
    </ul>


    <br>

    <h2>Build from source</h2>

    If you are Java developer, you will probably try to build whole thing from source code. All our current code is in
    SVN (we
    used CVS few years back). If you are not ready for a challenge, then try to download packaged software release.
    There will
    be pause between releases (6 months or more for major releases, minor releases will be released, when needed changes
    are
    done).


    <ul>

        <li>SVN:</li>
        <br>
        SVN system is current versioning system. You neeed to pull down whole tree. When builing with ANT,
        compiled files will be stored into ggc-support\bin folder from where you can directly run it.<br>

        Here is the link to the Sourceforge SVN Page:<br>
        <a href="http://sourceforge.net/svn/?groupId=49749">http://sourceforge.net/svn/?groupId=49749</a> <br><br>
        For details on how to check out sources see the Sourceforge SVN page.<br><br>

        <li>CVS:</li>
        <br>
        CVS system was deprecated (there are still old file there) when Sourceforge installed SVN, which is now the way
        to get sources.<br><br>
        <a href="http://sourceforge.net/cvs/?groupId=49749">http://sourceforge.net/cvs/?groupId=49749</a> <br><br>

    </ul>

    <br>

    <h2>Link to sourceforge files download area</h2>

    <a href="http://sourceforge.net/project/showfiles.php?groupId=49749">http://sourceforge.net/project/showfiles.php?groupId=49749</a><br>


    </ul>
</blockquote>
