<blockquote>

<center><h2 class="header">Screenshots [Pump Tool]</h2></center>


<h3>

<a href="index.php?show=screenshots" class="menu">Screenshots Main</a><br>

<a href="index.php?show=screenshots_daily" class="menu">Injection/Pen Theraphy</a><br>

<a href="index.php?show=screenshots_graph" class="menu">Graphs</a><br>

<a href="index.php?show=screenshots_tools" class="menu">Tools (Settings, Db)</a><br>

<a href="index.php?show=screenshots_print" class="menu">Printing</a><br>

<a href="index.php?show=screenshots_meter_tool" class="menu">Meter Tool</a><br>

Pump Tool<br>

<a href="index.php?show=screenshots_old" class="menu">Old Screenshots</a><br>

</h3>


<br>
<hr>
<br>

<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/daily_stats_pumps.jpg" border="0" alt="Daily Stats Pump View"></td></tr>
<tr><td>Daily Stats Pump View [preview only]</td></tr>
</table>


<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/manual_add_pump_data.jpg" border="0" alt="Manual Adding of Pump data"></td></tr>
<tr><td>Manual Adding of Pump data [preview only]</td></tr>
</table>

<br>
<br>


</blockquote>