<blockquote>

<center><h2 class="header">Screenshots [Meter Tool]</h2></center>


<h3>

<a href="index.php?show=screenshots" class="menu">Screenshots Main</a><br>

<a href="index.php?show=screenshots_daily" class="menu">Injection/Pen Theraphy</a><br>

<a href="index.php?show=screenshots_graph" class="menu">Graphs</a><br>

<a href="index.php?show=screenshots_tools" class="menu">Tools (Settings, Db)</a><br>

<a href="index.php?show=screenshots_print" class="menu">Printing</a><br>

Meter Tool<br>

<a href="index.php?show=screenshots_pump_tool" class="menu">Pump Tool</a><br>

<a href="index.php?show=screenshots_old" class="menu">Old Screenshots</a><br>

</h3>


<br>
<hr>
<br>


<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/read_meter_1.jpg" border="0" alt="Reading Meter 1"></td></tr>
<tr><td>Reading from Meter #1 - Pre-reading</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/read_meter_2.jpg" border="0" alt="Reading Meter 2"></td></tr>
<tr><td>Reading from Meter #2 - Reading</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/meter_config.jpg" border="0" alt="Meter Configuration"></td></tr>
<tr><td>Meter Configuration</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/meters_list.jpg" border="0" alt="Meters List"></td></tr>
<tr><td>Meters List</td></tr>
</table>


</blockquote>