<blockquote>

<center><h2 class="header">Screenshots [Main]</h2></center>


Since there are quite a lot of screenshots now (new functionalities) we decided to group them together,
so that no more than few are displayed at same time. Most screenshots are from version 0.4, but some are
older.

<h3>

Screenshots Main<br>

<a href="index.php?show=screenshots_daily" class="menu">Injection/Pen Theraphy</a><br>

<a href="index.php?show=screenshots_graph" class="menu">Graphs</a><br>

<a href="index.php?show=screenshots_tools" class="menu">Tools (Settings, Db)</a><br>

<a href="index.php?show=screenshots_print" class="menu">Printing</a><br>

<a href="index.php?show=screenshots_meter_tool" class="menu">Meter Tool</a><br>

<a href="index.php?show=screenshots_pump_tool" class="menu">Pump Tool</a><br>

<a href="index.php?show=screenshots_old" class="menu">Old Screenshots</a><br>

</h3>


<br>
<hr>
<br>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/main_ggc_0_4.gif" border="0" alt="Main Window of GGC 0.4"></td></tr>
<tr><td>Main Window of GGC 0.4</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="./images/help.bmp" border="0" alt="Help System"></td></tr>
<tr><td>Help System [Content not available yet]</td></tr>
</table>

<br>

</blockquote>