<blockquote>

<center><h2 class="header">Screenshots [Printing]</h2></center>


<h3>

<a href="index.php?show=screenshots" class="menu">Screenshots Main</a><br>

<a href="index.php?show=screenshots_daily" class="menu">Injection/Pen Theraphy</a><br>

<a href="index.php?show=screenshots_graph" class="menu">Graphs</a><br>

<a href="index.php?show=screenshots_tools" class="menu">Tools (Settings, Db)</a><br>

Printing<br>

<a href="index.php?show=screenshots_meter_tool" class="menu">Meter Tool</a><br>

<a href="index.php?show=screenshots_pump_tool" class="menu">Pump Tool</a><br>

<a href="index.php?show=screenshots_old" class="menu">Old Screenshots</a><br>

</h3>


<br>
<hr>
<br>



<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/print_report_prepare.jpg" border="0" alt="Printing (prepare)"></td></tr>
<tr><td>Printing (prepare)</td></tr>
</table>


<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/print_simple.gif" border="0" alt="Printing - Simple report (in Acrobat Viewer)"></td></tr>
<tr><td>Printing - Simple report (in Acrobat Viewer)</td></tr>
</table>


<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/print_extended.gif" border="0" alt="Printing - Extended report (in Acrobat Viewer)"></td></tr>
<tr><td>Printing - Extended report (in Acrobat Viewer)</td></tr>
</table>


<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/print_food_menu_selector.jpg" border="0" alt="Printing - Food Menu Selector"></td></tr>
<tr><td>Printing - Food Menu Selector</td></tr>
</table>





</blockquote>