<blockquote>

<center><h2 class="header">Screenshots [Old Screenshots]</h2></center>


This are some of old screenshots, which haven't been replaced yet (we are replacing and changing most
of dialogs)...

<h3>

<a href="index.php?show=screenshots" class="menu">Screenshots Main</a><br>

<a href="index.php?show=screenshots_daily" class="menu">Injection/Pen Theraphy</a><br>

<a href="index.php?show=screenshots_graph" class="menu">Graphs</a><br>

<a href="index.php?show=screenshots_tools" class="menu">Tools (Settings, Db)</a><br>

<a href="index.php?show=screenshots_print" class="menu">Printing</a><br>

<a href="index.php?show=screenshots_meter_tool" class="menu">Meter Tool</a><br>

<a href="index.php?show=screenshots_pump_tool" class="menu">Pump Tool</a><br>

Old Screenshots<br>

</h3>


<br>
<hr>
<br>


<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/0.3/main.gif" border="0" alt="Main Window of GGC 0.2.9"></td></tr>
<tr><td>Main Window of GGC 0.2.9</td></tr>
</table>

<br>
<br>

<table cellpadding="0" cellspacing="3" border="0" align="center" class="container">
<tr><td><img src="images/frequency.jpg" border="0" alt="Frequency Graph"></td></tr>
<tr><td>Frequency Graph</td></tr>
</table>

<br>
<br>



</blockquote>